return {
--   "folke/sidekick.nvim",
--   event = "LazyFile",
--   opts = {
--     cli = {
--       mux = {
--         backend = "zellij",
--         enabled = true,
--       },
--       win = {
--         width = 100,
--         height = 30,
--         layout = "float",
--         position = "right",
--       },
--     },
--   },
--   keys = {
--     {
--       "<Tab>",
--       function()
--         -- if there is a next edit, jump to it, otherwise apply it if any
--         if not require("sidekick").nes_jump_or_apply() then
--           return "<Tab>" -- fallback to normal tab
--         end
--         return "<tab>"
--       end,
--       expr = true,
--       desc = "Sidekick: Goto/Apply Next Edit",
--       mode = { "n" },
--     },
--     {
--       "<c-.>",
--       function()
--         require("sidekick.cli").focus()
--       end,
--       desc = "Sidekick: Switch Focus",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>aa",
--       function()
--         require("sidekick.cli").toggle({ focus = true })
--       end,
--       desc = "Sidekick: Toggle CLI",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>ac",
--       function()
--         require("sidekick.cli").toggle({ name = "claude", focus = true })
--       end,
--       desc = "Sidekick: Toggle Claude",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>ag",
--       function()
--         require("sidekick.cli").toggle({ name = "grok", focus = true })
--       end,
--       desc = "Sidekick: Toggle Grok",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>ap",
--       function()
--         require("sidekick.cli").select_prompt()
--       end,
--       desc = "Sidekick: Select Prompt",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>an",
--       function()
--         require("sidekick.nes").update()
--       end,
--       desc = "Sidekick: Request Next Edit",
--       mode = { "n" },
--     },
--     {
--       "<leader>aA",
--       function()
--         require("sidekick.nes").apply()
--       end,
--       desc = "Sidekick: Apply Next Edit",
--       mode = { "n" },
--     },
--     {
--       "<leader>ax",
--       function()
--         require("sidekick").clear()
--       end,
--       desc = "Sidekick: Clear Suggestions",
--       mode = { "n" },
--     },
--   },
}
