[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#141617" # Black
index = 16

[[colors.indexed_colors]]
color = "#fb4934" # Red
index = 17

[[colors.indexed_colors]]
color = "#83a598" # Green
index = 18

[[colors.indexed_colors]]
color = "#fabd2f" # Yellow
index = 19

[[colors.indexed_colors]]
color = "#83a598" # Blue
index = 20

[[colors.indexed_colors]]
color = "#d3869b" # Magenta
index = 21

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#83a598"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"

[colors.cursor]
cursor = "#d5c4a1"
text = "#141617"

[colors.normal]
black = "#141617"
red = "#fb4934"
green = "#83a598"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
white = "#d5c4a1"

[colors.primary]
background = "#000000"
foreground = "#d5c4a1"

[cursor]
unfocused_hollow = false

[cursor.vi_mode_style]
shape = "Beam"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# [terminal.shell]
# args = ["--login"]
# program = "/usr/bin/zsh"
#
[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true

[general]
live_config_reload = true
working_directory = "None"

[terminal]
